name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/python-peoples-crud-backend
            ${{ secrets.DOCKERHUB_USERNAME }}/python-peoples-crud-frontend
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # Não faz o push ainda
          tags: ${{ steps.meta.outputs.tags }}

      - name: Scan backend image with Trivy
        run: |
          # Escanear a imagem de backend com Trivy
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/python-peoples-crud-backend:latest
          trivy image --severity CRITICAL,HIGH --format json -o trivy-backend-report.json ${{ secrets.DOCKERHUB_USERNAME }}/python-peoples-crud-backend:latest
          
      - name: Upload backend Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-backend-report
          path: trivy-backend-report.json

      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false # Não faz o push ainda
          tags: ${{ steps.meta.outputs.tags }}

      - name: Scan frontend image with Trivy
        run: |
          # Escanear a imagem de frontend com Trivy
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/python-peoples-crud-frontend:latest
          trivy image --severity CRITICAL,HIGH --format json -o trivy-frontend-report.json ${{ secrets.DOCKERHUB_USERNAME }}/python-peoples-crud-frontend:latest

      - name: Upload frontend Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-frontend-report
          path: trivy-frontend-report.json

      - name: Push backend image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Push frontend image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
